### PR TITLE
fix test dependency

### PR DESCRIPTION
**Pull request by trishnaguha**
Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>
**Summary:**
Don't hard code dependency for tests.
This commit will point to `network-engine` when cloned from github or installed via tar and `ansible-network.network-engine` when installed via galaxy.

### CODE REVIEW

**Comment by trishnaguha** [comment]
recheck

**Comment by trishnaguha** [comment]
recheck

**Comment by trishnaguha** [comment]
recheck

**Comment by trishnaguha** [comment]
recheck

**Comment by trishnaguha** [comment]
recheck

**Comment by trishnaguha** [comment]
recheck

**Comment by trishnaguha** [comment]
recheck

**Review by privateip — APPROVED** [review]

**Review by rcarrillocruz — APPROVED** [review]

**Pull request merged**
