### PR TITLE
DNM: test a depends-on job

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
-Workflow

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Comment by rcarrillocruz** [comment]
recheck

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
rebuild

**Comment by gundalow** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
okay, zuul is working again @gundalow sounds like you don't want to use this default setting / jobs for linting. Is there something today you are using I can look at?

**Comment by gundalow** [comment]
I plan on updating the linter tools & rule in `ansible-network/ansible-zuul-jobs`

**Comment by gundalow** [comment]
https://github.com/ansible-network/zuul-config/pull/8 which updates to use `ansible-network/ansible-zuul-jobs` has been merged

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
Previous run wasn't using `ansible-network/ansible-zuul-jobs`, rerunning to see if it's been processed.

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
recheck

**Comment by pabelanger** [comment]
So, I think what we can do here is create a new job (other then ansible-lint) and update this job to use it.  Because, we do still need sf-jobs in the base job as it has roles for publishing logs.

I think a way moving forward here, would then be to shadow sf-jobs so you can override the ansible-lint jobs with your own version

**Comment by TristanCacqueray** [comment]
recheck

**Pull request closed without merging**
