### PR TITLE
Add vlan_expand, vlan_compress filter plugins

### LINKED ISSUE #62: Filter: vlan_compress
Compress a vlan list 

1,2,3,4,5 becomes 1-5
1,2,4,5 becomes 1-2,4-5
1,2,3,5 becomes 1-3,5

### LINKED ISSUE #63: Filter: vlan_expand
Expand a vlan string to its elements

vlan1,3-5,7 expands to 1,3,4,5,7
vlan1-5 expands to 1,2,3,4,5

### PR DESCRIPTION
**Pull request by trishnaguha**
Fixes #62 
Fixes #63

### CODE REVIEW

**Review by gundalow — COMMENTED** [review]
Can you please add a `fragment`, no need to rebuild CHANGELOG till we do the release

**Comment by trishnaguha** [comment]
@gundalow added.

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
ERROR: role-to-test/filter_plugins/network_engine.py:105:1: E303 too many blank
ERROR: role-to-test/filter_plugins/network_engine.py:84:14: undefined-variable Undefined variable 'FilterError'

**Review by privateip — APPROVED** [review]

**Pull request merged**
